// GitHub Actions workflow that runs the saved tests. Secrets come from GitHub Secrets under the same names
// (SECRET_X in the job = secret X); environment values from the repository variable E2E_VARS (JSON).
export function ciWorkflow({ secrets = [] } = {}) {
  const env = secrets.map(n => `          SECRET_${n}: \${{ secrets.${n} }}`).join('\n');
  return `# Generated by ABRA (Saved tests > Export CI workflow). Safe to edit.
# Runs on GitHub's servers: tests must target an address reachable from the internet (staging), not *.test.
name: E2E tests

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      tests:
        description: 'Test files to run, space separated (empty = all), e.g. tests/my-project (one project) or tests/my-project/smoke.spec.ts'
        required: false
        default: ''

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - name: App unit tests
        run: npm run test:app
      - name: Saved tests
        run: npx playwright test \${{ github.event.inputs.tests }}
        env:
          CI: 'true'
          E2E_VARS: \${{ vars.E2E_VARS }}
${env}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 14
`;
}
